"""Public API for the provider-neutral immutable Step29 ChangeSet."""

from .builder import ChangeSetBuilder
from .contracts import (
    ApprovalScopeDefinitionRef,
    BoundOperationEvidence,
    CanonicalChangeOperation,
    CanonicalChangeSet,
    CanonicalOperationContractEvidence,
    ChangeDependency,
    ChangePrecondition,
    ChangeSetBuildRequest,
    ChangeSetError,
    DerivedOperationMaterialization,
    OperationOrigin,
    OperationSourceEvidence,
    OperationSourceKind,
    PreconditionKind,
    SemanticImpactEvidence,
    ValidationTask,
    ValidationTaskKind,
)
from .hashing import (
    canonical_hash,
    canonical_json,
    compute_bound_operation_evidence_fingerprint,
    compute_bound_operation_fingerprint,
    compute_changeset_hash,
    compute_contract_definition_fingerprint,
    compute_operation_semantic_hash,
    compute_proposed_change_hash,
    compute_scope_rule_fingerprint,
)
from .integrity import validate_changeset_integrity

__all__ = [
    "ApprovalScopeDefinitionRef",
    "BoundOperationEvidence",
    "CanonicalChangeOperation",
    "CanonicalChangeSet",
    "CanonicalOperationContractEvidence",
    "ChangeDependency",
    "ChangePrecondition",
    "ChangeSetBuildRequest",
    "ChangeSetBuilder",
    "ChangeSetError",
    "DerivedOperationMaterialization",
    "OperationOrigin",
    "OperationSourceEvidence",
    "OperationSourceKind",
    "PreconditionKind",
    "SemanticImpactEvidence",
    "ValidationTask",
    "ValidationTaskKind",
    "canonical_hash",
    "canonical_json",
    "compute_bound_operation_evidence_fingerprint",
    "compute_bound_operation_fingerprint",
    "compute_changeset_hash",
    "compute_contract_definition_fingerprint",
    "compute_operation_semantic_hash",
    "compute_proposed_change_hash",
    "compute_scope_rule_fingerprint",
    "validate_changeset_integrity",
]
